swagger: '2.0'

info:
  version: "1.0.0"
  title: Offline Mode API
  description: This file defines the API for offline mode.  
  x-api-type: public
  x-api-required: false

paths:
  /Offline/State:
    get:
      description: Get offline mode state
      responses:
        200:
          description: Current state
          schema:
            $ref: '#/definitions/OfflineState'
    put:
      description: Request state change
      parameters:
          - name: state
            in: body
            description: New state
            required: true
            schema:
              $ref: '#/definitions/OfflineState'
      responses:
        200:
          description: State change accepted
        403:
          description: State change declined

  /Offline/State/Subscription:
    post:
      description: Subscribe to offline state change events
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: New state changed
          schema:
            $ref: '#/definitions/OfflineState'
    delete:
      description: Unsubscribe from offline state change events
      responses:
        200:
          description: Operation completed successfully

  /Offline/Config:
    get:
      description: Get offline mode settings
      responses:
        200:
          description: Configuration data structure
          schema:
            $ref: '#/definitions/OfflineConfig'
    put:
      description: Set offline mode settings
      parameters:
          - name: config
            in: body
            description: New configuration for offline mode
            required: true
            schema:
              $ref: '#/definitions/OfflineConfig'
      responses:
        200:
          description: Configuration changed succesfully
        400:
          description: Invalid configuration

  /Offline/Config/Subscription:
    post:
      description: Subscribe to offline configuration change events
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: New state changed
          schema:
            $ref: '#/definitions/OfflineConfig'
    delete:
      description: Unsubscribe from offline configuration change events
      responses:
        200:
          description: Operation completed successfully

definitions:
  OfflineConfig:
    required:
      - WakeUpBehavior
      - MeasurementParams
      - SleepDelay
      - Options
    properties:
      WakeUpBehavior:
        description: Configure how the device wakes up
        $ref: "#/definitions/OfflineWakeup"
      MeasurementParams:
        description: 
          Array of measurement parameters (samplerate/interval).
        type: array
        minItems: 8
        maxItems: 8
        items:
          type: integer
          format: uint16
          x-unit: Hz
      SleepDelay:
        description: Enter sleep mode automatically after set amount of time with no input
        type: integer
        format: uint16
        x-unit: s
      Options:
        description: Additional configuration flags
        type: integer
        format: uint8
          
  OfflineState:
    type: integer
    format: uint8
    enum:
    - name: "INIT"
      description: Offline mode is initializing
      value: 0
    - name: "RUNNING"
      description: Default operation
      value: 1
    - name: "CONNECTED"
      description: Device is connected with Bluetooth
      value: 2
    - name: "SLEEP"
      description: Powersave mode with BLE advertising turned off, logging disabled
      value: 3
    - name: "ERROR_SYSTEM_FAILURE"
      description: Generic failure mode
      value: 4
    - name: "ERROR_INVALID_CONFIG"
      description: Offline mode configuration is invalid
      value: 5 
    - name: "ERROR_STORAGE_FULL"
      description: Offline data storage is full
      value: 6
    - name: "ERROR_BATTERY_LOW"
      description: "The battery is low. Writing to flash is no longer reliable."
      value: 7

  OfflineWakeup:
    type: integer
    format: uint8
    enum:
    - name: 'AlwaysOn'
      description: Sleep disabled if no flags present
      value: 0
    - name: 'Connector'
      description: Wake up from connector
      value: 1
    - name: 'Movement'
      descrioton: Wake up from any movement
      value: 2
    - name: 'DoubleTap'
      description: Wake up from double tap
      value: 3

  OfflineOptionsFlags:    
    type: integer
    format: uint8
    enum:
    - name: 'LogTapGestures'
      description: Set to log tap gestures
      value: 1
    - name: 'LogShakeGestures'
      description: Set to log tap gestures
      value: 2
    - name: 'CompressECGSamples'
      description: Set to enable additional ECG compression
      value: 4
    - name: 'ShakeToConnect'
      description: Set to enable BLE advertising when shaking the device
      value: 8
    - name: 'TripleTapToStartLog'
      description: Start a new log by tapping the device three times
      value: 16

datalogger:
  version: "1.0"
  type: "config"

  resources:
    /Offline/Config:
      array-lengths: 8
