swagger: '2.0'

info:
  version: "0.0.1"
  title: Offline Mode API
  description: This file defines the API for offline mode.

paths:
  /Offline/State:
    get:
      description: Get offline mode state
      responses:
        200:
          description: Current state
          schema:
            $ref: '#/definitions/OfflineState'
    put:
      description: Request state change
      parameters:
          - name: state
            in: body
            description: New state
            required: true
            schema:
              $ref: '#/definitions/OfflineState'
      responses:
        200:
          description: State change accepted
        403:
          description: State change declined

  /Offline/State/Subscription:
    post:
      description: Subscribe to offline state change events
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: New state changed
          schema:
            $ref: '#/definitions/OfflineState'
    delete:
      description: Unsubscribe from offline state change events
      responses:
        200:
          description: Operation completed successfully

  /Offline/Config:
    get:
      description: Get offline mode settings
      responses:
        200:
          description: Configuration data structure
          schema:
            $ref: '#/definitions/OfflineConfig'
    put:
      description: Set offline mode settings
      parameters:
          - name: config
            in: body
            description: New configuration for offline mode
            required: true
            schema:
              $ref: '#/definitions/OfflineConfig'
      responses:
        200:
          description: Configuration changed succesfully
        400:
          description: Invalid configuration

  /Offline/Config/Subscription:
    post:
      description: Subscribe to offline configuration change events
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: New state changed
          schema:
            $ref: '#/definitions/OfflineConfig'
    delete:
      description: Unsubscribe from offline configuration change events
      responses:
        200:
          description: Operation completed successfully

  /Offline/Data:
    post:
      description: (TESTING) Records given block of data
      parameters:
        - name: data
          in: body
          description: Block of data
          required: true
          schema:
            $ref: '#/definitions/OfflineDataBlock'
      responses:
        200:
          description: Operation completed successfully
        400:
          description: Failed to record block of data

    delete:
      description: Erase all recorded data
      responses:
        200:
          description: Operation completed successfully
        400:
          description: Operation is not permitted (data recording is active)

  /Offline/Data/Subscription:
    post:
      description: Subscribe to receive data blocks
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: Compressed block of data
          schema:
            $ref: '#/definitions/OfflineDataBlock'
    delete:
      description: Unsubscribe from offline data blocks
      responses:
        200:
          description: Operation completed successfully

definitions:
  OfflineConfig:
    required:
      - WakeUpBehavior
      - SampleRates
      - SleepDelay
    properties:
      WakeUpBehavior:
        description: Configure how the device wakes up
        $ref: "#/definitions/OfflineWakeup"
      SampleRates:
        description: Array of samplerates for each sensor indexed by MeasurementSensors enum.
        type: array
        minItems: 6
        maxItems: 6
        items:
          type: integer
          format: uint16
          x-unit: Hz
      SleepDelay:
        description: Enter sleep mode automatically after set amount of time with no input
        type: integer
        format: uint16
        x-unit: s

  OfflineDataBlock:
    required:
      - Data
    properties:
      Data:
        description: Data bytes
        type: array
        items:
          type: integer
          format: uint8
          
  OfflineState:
    type: integer
    format: uint8
    enum:
    - name: "INIT"
      description: Offline mode is initializing
      value: 0
    - name: "RUNNING"
      description: Default operation
      value: 1
    - name: "CONNECTED"
      description: Device is connected with Bluetooth
      value: 2
    - name: "ERROR_SYSTEM_FAILURE"
      description: Generic failure mode
      value: 3
    - name: "ERROR_INVALID_CONFIG"
      description: Offline mode configuration is invalid
      value: 4 
    - name: "ERROR_STORAGE_FULL"
      description: Offline data storage is full
      value: 5
    - name: "ERROR_BATTERY_LOW"
      description: "The battery is low. Writing to flash is no longer reliable."
      value: 6

  OfflineWakeup:
    type: integer
    format: uint8
    enum:
    - name: 'AlwaysOn'
      description: Sleep disabled if no flags present
      value: 0
    - name: 'Connector'
      description: Wake up from connector
      value: 1
    - name: 'Movement'
      descrioton: Wake up from any movement
      value: 2
    - name: 'SingleTap'
      description: Wake up from single tap
      value: 3
    - name: 'DoubleTap'
      description: Wake up from double tap
      value: 4

  OfflineMeasurement:
    type: integer
    format: uint8
    enum:
    - name: 'ECG'
      description: ECG
      value: 0
    - name: 'HR'
      description: Heartrate
      value: 1
    - name: 'ACC'
      description: Acceleration
      value: 2
    - name: 'GYRO'
      description: Gyroscope
      value: 3
    - name: 'MAGN'
      description: Magnetometer
      value: 4
    - name: 'TEMP'
      description: Temperature
      value: 5
    - name: 'COUNT'
      description: Number of measurements
      value: 6
