swagger: '2.0'

info:
  version: "0.0.1"
  title: Offline Mode API
  description: This file defines the API for offline mode.

paths:
  /Offline/State:
    get:
      description: Get offline mode state
      responses:
        200:
          description: Current state
          schema:
            $ref: '#/definitions/OfflineState'

  /Offline/State/Subscription:
    post:
      description: Subscribe to offline state change events
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: New state changed
          schema:
            $ref: '#/definitions/OfflineState'
    delete:
      description: Unsubscribe from offline state change events
      responses:
        200:
          description: Operation completed successfully

  /Offline/Config:
    get:
      description: Get offline mode settings
      responses:
        200:
          description: Configuration data structure
          schema:
            $ref: '#/definitions/OfflineConfig'
    put:
      description: Set offline mode settings
      parameters:
          - name: config
            in: body
            description: New configuration for offline mode
            required: true
            schema:
              $ref: '#/definitions/OfflineConfig'
      responses:
        200:
          description: Configuration changed succesfully
        400:
          description: Invalid configuration

  /Offline/Config/Subscription:
    post:
      description: Subscribe to offline configuration change events
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: New state changed
          schema:
            $ref: '#/definitions/OfflineConfig'
    delete:
      description: Unsubscribe from offline configuration change events
      responses:
        200:
          description: Operation completed successfully
        
  /Offline/Sessions:
    get:
      description: Get list of offline session logs and information about them.
      responses:
        200:
          description: List of session logs
          schema:
            $ref: "#/definitions/OfflineSessionList"
    delete:
      description: Clear offline session logs
      responses:
        200:
          description: "Offline data cleared"

  /Offline/Sessions/Subscription:
    post:
      description: Subscribe to receive session lists
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: Compressed block of data
          schema:
            $ref: "#/definitions/OfflineSessionList"
    delete:
      description: Unsubscribe from session lists
      responses:
        200:
          description: Operation completed successfully

  /Offline/Sessions/{SessionIndex}:
    parameters:
      - $ref: '#/parameters/SessionIndex'
    get:
      description: Get offline data blocks
      responses:
        100:
          description: Block transferred, incomplete data
          schema:
            $ref: '#/definitions/OfflineData'
        200:
          description: Block transferred, the data is complete
          schema:
            $ref: '#/definitions/OfflineData'

  /Offline/Data/Subscription:
    post:
      description: Subscribe to receive compressed data blocks (for DataLogger)
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: Compressed block of data
          schema:
            $ref: '#/definitions/OfflineData'
    delete:
      description: Unsubscribe from offline data blocks
      responses:
        200:
          description: Operation completed successfully

definitions:
  OfflineConfig:
    required:
      - WakeUpBehavior
      - SampleRates
      - SleepDelay
    properties:
      WakeUpBehavior:
        description: Configure how the device wakes up
        $ref: "#/definitions/WakeUpBehavior"
      SampleRates:
        description: Array of samplerates for each sensor indexed by MeasurementSensors enum.
        type: array
        items:
          type: integer
          format: uint16
          x-unit: Hz
      SleepDelay:
        description: Enter sleep mode automatically after set amount of time with no input
        type: integer
        format: uint16
        x-unit: s

  OfflineSession:
    required:
      - StartTime
      - EndTime
    properties:
      StartTime:
        description: Start timestamp (epoch)
        type: integer
        format: uint64
      EndTime:
        description: End timestamp (epoch)
        type: integer
        format: uint64
  
  OfflineSessionList:
    required:
      - Items
    properties:
      Items:
        description: List of sessions
        type: array
        items:
          $ref: "#/definitions/OfflineSession"

  OfflineData:
    required:
      - SessionIndex
      - Offset
      - Bytes
    properties:
      SessionIndex:
        description: Session index
        type: integer
        format: uint32
      Offset:
        description: Data offset
        type: integer
        format: uint32
      Bytes:
        description: Data bytes
        type: array
        items:
          type: integer
          format: uint8

  OfflineState:
    type: integer
    format: uint8
    enum:
    - name: "INIT"
      description: Offline mode is initializing
      value: 0
    - name: "IDLE"
      description: Offline mode is ready but not active
      value: 1
    - name: "ACTIVE"
      description: Offline mode is currently active
      value: 2
    - name: "ERROR_INVALID_CONFIG"
      description: Offline mode configuration is invalid
      value: 3 
    - name: "ERROR_STORAGE_FULL"
      description: Offline data storage is full
      value: 4
    - name: "ERROR_BATTERY_LOW"
      description: "The battery is low. Writing to flash is no longer reliable."
      value: 5

  WakeUpBehavior:
    type: integer
    format: uint8
    enum:
    - name: 'AlwaysOn'
      description: Sleep disabled if no flags present
      value: 0
    - name: 'HR'
      description: Wake up on HR or when touching the pins.
      value: 1
    - name: 'Movement'
      descrioton: Wake up from any movement
      value: 2
    - name: 'SingleTapOn'
      description: Wake up from single tap
      value: 3
    - name: 'SingleTapOnOff'
      description: Wake up and enter sleep from single tap
      value: 4
    - name: 'DoubleTapOn'
      description: Wake up from double tap
      value: 5
    - name: 'DoubleTapOnOff'
      description: Wake up and enter sleep from double tap
      value: 6

  MeasurementSensors:
    type: integer
    format: uint8
    enum:
    - name: 'ECG'
      description: ECG
      value: 0
    - name: 'HR'
      description: Heartrate
      value: 1
    - name: 'ACC'
      description: Acceleration
      value: 2
    - name: 'GYRO'
      description: Gyroscope
      value: 3
    - name: 'MAGN'
      description: Magnetometer
      value: 4
    - name: 'TEMP'
      description: Temperature
      value: 5
    - name: 'COUNT'
      description: Number of measurements
      value: 6

parameters:
  SessionIndex:
    name: SessionIndex
    in: path
    required: true
    type: integer
    format: uint32
