swagger: '2.0'

info:
  version: "0.0.1"
  title: Offline Measurement API
  description: This file defines the API for offline measurements.
  x-api-type: public
  x-api-required: false

paths:

  /Offline/Meas/ECG/{SampleRate}:
    parameters:
      - $ref: '#/parameters/SampleRate'

  /Offline/Meas/ECG/{SampleRate}/Subscription:
    parameters:
      - $ref: '#/parameters/SampleRate'
    post:
      description: Subscribe to offline optimized ECG measurements
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: Offline optimized ECG data
          schema:
            $ref: '#/definitions/OfflineECGData'
    delete:
      description: Unsubscribe from offline optimized ECG measurements
      responses:
        200:
          description: Operation completed successfully

  /Offline/Meas/ECG/Compressed/{SampleRate}:
    parameters:
      - $ref: '#/parameters/SampleRate'
       
  /Offline/Meas/ECG/Compressed/{SampleRate}/Subscription:
    parameters:
      - $ref: '#/parameters/SampleRate'
    post:
      description: 
        Subscribe to offline optimized ECG measurements
        that utilize additional compression techniques (experimental)
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: Compressed ECG data
          schema:
            $ref: '#/definitions/OfflineECGCompressedData'
    delete:
      description: Unsubscribe from offline optimized ECG measurements
      responses:
        200:
          description: Operation completed successfully

  /Offline/Meas/HR/Subscription:
    post:
      description: Subscribe to offline optimized HR (average) measurements
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: Offline optimized HR data
          schema:
            $ref: '#/definitions/OfflineHRData'
    delete:
      description: Unsubscribe from offline optimized HR measurements
      responses:
        200:
          description: Operation completed successfully

  /Offline/Meas/RR/Subscription:
    post:
      description: Subscribe to offline optimized RR measurements
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: Offline optimized RR data
          schema:
            $ref: '#/definitions/OfflineRRData'
    delete:
      description: Unsubscribe from offline optimized RR measurements
      responses:
        200:
          description: Operation completed successfully

  /Offline/Meas/Acc/{SampleRate}:
    parameters:
      - $ref: '#/parameters/SampleRate'

  /Offline/Meas/Acc/{SampleRate}/Subscription:
    parameters:
      - $ref: '#/parameters/SampleRate'
    post:
      description: Subscribe to offline optimized acceleration measurements
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: Offline optimized linear acceleration data
          schema:
            $ref: '#/definitions/OfflineAccData'
    delete:
      description: Unsubscribe from offline optimized acceleration measurements
      responses:
        200:
          description: Operation completed successfully

  /Offline/Meas/Gyro/{SampleRate}:
    parameters:
      - $ref: '#/parameters/SampleRate'

  /Offline/Meas/Gyro/{SampleRate}/Subscription:
    parameters:
      - $ref: '#/parameters/SampleRate'
    post:
      description: Subscribe to offline optimized angular velocity measurements
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: Offline optimized gyro data
          schema:
            $ref: '#/definitions/OfflineGyroData'
    delete:
      description: Unsubscribe from offline optimized angular velocity measurements
      responses:
        200:
          description: Operation completed successfully

  /Offline/Meas/Magn/{SampleRate}:
    parameters:
      - $ref: '#/parameters/SampleRate'

  /Offline/Meas/Magn/{SampleRate}/Subscription:
    parameters:
      - $ref: '#/parameters/SampleRate'
    post:
      description: Subscribe to offline optimized magnetometer measurements
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: Offline optimized magnetometer data
          schema:
            $ref: '#/definitions/OfflineMagnData'
    delete:
      description: Unsubscribe from offline optimized magnetometer measurements
      responses:
        200:
          description: Operation completed successfully

  /Offline/Meas/Temp/Subscription:
    post:
      description: Subscribe to offline optimized temperature measurements
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: Offline optimized temperature data
          schema:
            $ref: '#/definitions/OfflineTempData'
    delete:
      description: Unsubscribe from offline optimized temperature measurements
      responses:
        200:
          description: Operation completed successfully

  /Offline/Meas/Activity/Subscription:
    post:
      description: |
        Subscribe to activity based on movement. 
        Once a minute, creates a value that has been accumulated based on linear acceleration.
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: Average acceleration during a minute
          schema:
            $ref: '#/definitions/OfflineActivityData'
    delete:
      description: Unsubscribe from activity.
      responses:
        200:
          description: Operation completed successfully

parameters:

  SampleRate:
    name: SampleRate
    in: path
    required: true
    type: integer
    format: int32

definitions:

  OfflineTimestamp:
    type: integer
    format: uint32
    x-unit: millisecond

  OfflineECGData:
    required:
      - Timestamp
      - SampleData
    properties:
      Timestamp:
        description: Local timestamp of the first measurement
        $ref: "#/definitions/OfflineTimestamp"
      SampleData:
        description: 16-bit samples in byte array
        type: array
        items:
          type: integer
          format: int16
          x-unit: bpm

  OfflineECGCompressedData:
    required:
      - Timestamp
      - Bytes
    properties:
      Timestamp:
        description: Local timestamp of the first measurement
        $ref: "#/definitions/OfflineTimestamp"
      Bytes:
        description:
          16-bit samples compressed using deltas 
          and variable-length coding as 32 byte chunks
        type: array
        items:
          type: integer
          format: uint8

  OfflineHRData:
    required:
        - Timestamp
        - Average
    properties:
      Timestamp:
        description: Local timestamp
        $ref: "#/definitions/OfflineTimestamp"
      Average:
        description: Average heartrate
        type: integer
        format: uint8
        x-unit: bpm
        minimum: 0.0
        maximum: 250.0

  OfflineRRData:
    required:
      - Timestamp
      - IntervalData
    properties:
      Timestamp:
        description: Local timestamp of the first measurement
        $ref: "#/definitions/OfflineTimestamp"
      IntervalData:
        description: |
          Bit-packed chunk of 4 x 12-bit RR-intervals (6 bytes in total).
          RR-intervals are reported in milliseconds.
        type: array
        items:
          type: integer
          format: uint8

  OfflineAccData:
    required:
      - Timestamp
      - Measurements
    properties:
      Timestamp:
        description: Local timestamp of the first measurement
        $ref: "#/definitions/OfflineTimestamp"
      Measurements:
        type: array
        x-unit: m/s^2
        description: Byte array of 3D vectors with 24-bit fixed-point components.
        items:
          $ref: "#/definitions/Vec3_Q12_12"

  OfflineGyroData:
    required:
      - Timestamp
      - Measurements
    properties:
      Timestamp:
        description: Local timestamp of the first measurement
        $ref: "#/definitions/OfflineTimestamp"
      Measurements:
        description: |
          Measured angular velocity values (3D) in array.
          Represented as a byte array of 3D vectors with 24-bit fixed-point components.
        type: array
        x-unit: dps (degree per second)
        items:
          $ref: "#/definitions/Vec3_Q12_12"

  OfflineMagnData:
    required:
      - Timestamp
      - Measurements
    properties:
      Timestamp:
        description: Local timestamp of the first measurement
        $ref: "#/definitions/OfflineTimestamp"
      Measurements:
        type: array
        x-unit: microtesla
        items:
          $ref: "#/definitions/Vec3_Q10_6"

  OfflineTempData:
    required:
      - Timestamp
      - Measurement
    properties:
      Timestamp:
        description: Local timestamp of the first measurement
        $ref: "#/definitions/OfflineTimestamp"
      Measurement:
        type: integer
        format: int8
        description: Temperature as 8-bit signed integer
        minimum: -128
        maximum: 127
        x-unit: celsius

  OfflineActivityData:
    required:
      - Timestamp
      - Activity
    properties:
      Timestamp:
        description: Local timestamp of the measurement
        $ref: "#/definitions/OfflineTimestamp"
      Activity:
        description: Value representing user activity based on linear acceleration.
        $ref: "#/definitions/Q10_6"

  Vec3_Q16_8:
    required:
      - x
      - y
      - z
    properties:
      x:
        $ref: "#/definitions/Q16_8"
      y:
        $ref: "#/definitions/Q16_8"
      z:
        $ref: "#/definitions/Q16_8"

  Vec3_Q10_6:
    required:
      - x
      - y
      - z
    properties:
      x:
        $ref: "#/definitions/Q10_6"
      y:
        $ref: "#/definitions/Q10_6"
      z:
        $ref: "#/definitions/Q10_6"

  Vec3_Q12_12:
    required:
      - x
      - y
      - z
    properties:
      x:
        $ref: "#/definitions/Q12_12"
      y:
        $ref: "#/definitions/Q12_12"
      z:
        $ref: "#/definitions/Q12_12"

  Q16_8:
    required:
      - B0
      - B1
      - B2
    properties:
      B0:
        type: integer
        format: uint8
      B1:
        type: integer
        format: uint8
      B2:
        type: integer
        format: int8

  Q12_12:
    required:
      - B0
      - B1
      - B2
    properties:
      B0:
        type: integer
        format: uint8
      B1:
        type: integer
        format: uint8
      B2:
        type: integer
        format: int8

  Q10_6:
    required:
      - B0
      - B1
    properties:
      B0:
        type: integer
        format: uint8
      B1:
        type: integer
        format: int8

datalogger:
  version: "1.0"
  type: "config"

  resources:
    /Offline/Meas/ECG/.*:
      array-lengths: 16
    /Offline/Meas/ECG/Compressed/.*:
      array-lengths: 32
    /Offline/Meas/RR:
      array-lengths: 12
    /Offline/Meas/Acc/.*:
      array-lengths: 1,2,4,8
    /Offline/Meas/Gyro/.*:
      array-lengths: 1,2,4,8
    /Offline/Meas/Magn/.*:
      array-lengths: 1,2,4,8
