swagger: '2.0'

info:
  version: "0.0.1"
  title: Offline Measurement API
  description: This file defines the API for offline measurements.
  x-api-type: public
  x-api-required: false

paths:
  /Offline/Meas/ECG/Subscription:
    post:
      description: Subscribe to offline optimized ECG measurements
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: Offline optimized ECG data
          schema:
            $ref: '#/definitions/OfflineECGData'
    delete:
      description: Unsubscribe from offline optimized ECG measurements
      responses:
        200:
          description: Operation completed successfully

  /Offline/Meas/HR/Subscription:
    post:
      description: Subscribe to offline optimized HR and RR measurements
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: Offline optimized HR and RR data
          schema:
            $ref: '#/definitions/OfflineHRData'
    delete:
      description: Unsubscribe from offline optimized HR and RR measurements
      responses:
        200:
          description: Operation completed successfully

  /Offline/Meas/Acc/Subscription:
    post:
      description: Subscribe to offline optimized acceleration measurements
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: Offline optimized linear acceleration data
          schema:
            $ref: '#/definitions/OfflineAccData'
    delete:
      description: Unsubscribe from offline optimized acceleration measurements
      responses:
        200:
          description: Operation completed successfully

  /Offline/Meas/Gyro/Subscription:
    post:
      description: Subscribe to offline optimized angular velocity measurements
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: Offline optimized gyro data
          schema:
            $ref: '#/definitions/OfflineGyroData'
    delete:
      description: Unsubscribe from offline optimized angular velocity measurements
      responses:
        200:
          description: Operation completed successfully

  /Offline/Meas/Magn/Subscription:
    post:
      description: Subscribe to offline optimized magnetometer measurements
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: Offline optimized magnetometer data
          schema:
            $ref: '#/definitions/OfflineMagnData'
    delete:
      description: Unsubscribe from offline optimized magnetometer measurements
      responses:
        200:
          description: Operation completed successfully

  /Offline/Meas/Temp/Subscription:
    post:
      description: Subscribe to offline optimized temperature measurements
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: Offline optimized temperature data
          schema:
            $ref: '#/definitions/OfflineTempData'
    delete:
      description: Unsubscribe from offline optimized temperature measurements
      responses:
        200:
          description: Operation completed successfully

definitions:

  OfflineECGData:
    required:
      - Timestamp
      - SampleData
    properties:
      Timestamp:
        description: Local timestamp of the first measurement
        $ref: "#/definitions/OfflineTimestamp"
      SampleData:
        description: 16-bit samples in byte array
        type: array
        items:
          type: integer
          format: int16
          x-unit: bpm

  OfflineHRData:
    required:
        - Average
        - rrValues
    properties:
      Average:
        description: Average heartrate
        type: integer
        format: uint8
        x-unit: bpm
        minimum: 0.0
        maximum: 250.0
      rrValues:
        description: |
          RR-interval returns all the intervals in milliseconds. By default,
          single rr-interval value is returned after each heart beat.
        type: array
        minItems: 1
        maxItems: 60
        items:
          type: integer
          format: uint16
          x-unit: ms
          minimum: 240    # equals in HR 250 bpm
          maximum: 4000   # equals in HR 15 bpm

  OfflineAccData:
    required:
      - Timestamp
      - Measurements
    properties:
      Timestamp:
        description: Local timestamp of the first measurement
        $ref: "#/definitions/OfflineTimestamp"
      Measurements:
        type: array
        x-unit: m/s^2
        description: Byte array of 3D vectors with 24-bit fixed-point components.
        items:
          $ref: "#/definitions/Vec3_Q12_12"

  OfflineGyroData:
    required:
      - Timestamp
      - Measurements
    properties:
      Timestamp:
        description: Local timestamp of the first measurement
        $ref: "#/definitions/OfflineTimestamp"
      Measurements:
        description: |
          Measured angular velocity values (3D) in array.
          Represented as a byte array of 3D vectors with 24-bit fixed-point components.
        type: array
        x-unit: dps (degree per second)
        items:
          $ref: "#/definitions/Vec3_Q12_12"

  OfflineMagnData:
    required:
      - Timestamp
      - Measurements
    properties:
      Timestamp:
        description: Local timestamp of the first measurement
        $ref: "#/definitions/OfflineTimestamp"
      Measurements:
        type: array
        x-unit: microtesla
        items:
          $ref: "#/definitions/Vec3_Q10_6"

  OfflineTempData:
    required:
      - Timestamp
      - Measurement
    properties:
      Timestamp:
        description: Local timestamp of the first measurement
        $ref: "#/definitions/OfflineTimestamp"
      Measurement:
        type: integer
        format: int8
        description: Temperature as 8-bit signed integer
        minimum: -128
        maximum: 127
        x-unit: celsius

  OfflineTimestamp:
    type: integer
    format: uint32
    x-unit: millisecond

  Vec3_Q16_8:
    required:
      - x
      - y
      - z
    properties:
      x:
        $ref: "#/definitions/Q16_8"
      y:
        $ref: "#/definitions/Q16_8"
      z:
        $ref: "#/definitions/Q16_8"

  Vec3_Q10_6:
    required:
      - x
      - y
      - z
    properties:
      x:
        $ref: "#/definitions/Q10_6"
      y:
        $ref: "#/definitions/Q10_6"
      z:
        $ref: "#/definitions/Q10_6"

  Vec3_Q12_12:
    required:
      - x
      - y
      - z
    properties:
      x:
        $ref: "#/definitions/Q12_12"
      y:
        $ref: "#/definitions/Q12_12"
      z:
        $ref: "#/definitions/Q12_12"

  Q16_8:
    required:
      - Integer
      - Fraction
    properties:
      Integer:
        type: integer
        format: int16
      Fraction:
        type: integer
        format: uint8

  Q12_12:
    required:
      - B0
      - B1
      - B2
    properties:
      B0:
        type: integer
        format: uint8
      B1:
        type: integer
        format: uint8
      B2:
        type: integer
        format: uint8

  Q10_6:
    required:
      - Value
    properties:
      Value:
        type: integer
        format: int16

datalogger:
  version: "1.0"
  type: "config"

  resources:
    /Offline/Meas/ECG/.*:
      array-lengths: 16
    /Offline/Meas/Acc/.*:
      array-lengths: 1,2,4,8
    /Offline/Meas/Gyro/.*:
      array-lengths: 1,2,4,8
    /Offline/Meas/Magn/.*:
      array-lengths: 1,2,4,8
